plugins {
    id 'com.android.application'
}

android {
    namespace 'com.codex.expensekeeper'
    compileSdk 34

    defaultConfig {
        applicationId 'com.codex.expensekeeper'
        minSdk 23
        targetSdk 34
        versionCode 2
        versionName '1.0.1'
    }

    flavorDimensions 'market'

    productFlavors {
        bazaar {
            dimension 'market'
            resValue 'string', 'market_name', 'Bazaar'
            resValue 'string', 'share_app_url', 'https://cafebazaar.ir/app/com.codex.expensekeeper'
            manifestPlaceholders = [marketName: 'bazaar']
        }

        myket {
            dimension 'market'
            resValue 'string', 'market_name', 'Myket'
            resValue 'string', 'share_app_url', 'https://myket.ir/app/com.codex.expensekeeper'
            manifestPlaceholders = [marketName: 'myket']
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
